<?php
return [
	'VONAGE_API_KEY' => env('VONAGE_API_KEY', 'bf1a95ae'),
	'VONAGE_API_SECRET' => env('VONAGE_API_SECRET', 'myjBgYaHGZvRLds8'),
	'VONAGE_API_SIGNATURE_SECRET' => env('VONAGE_API_SIGNATURE_SECRET', '6lIW0WDqUSL446xZbewcUpCZpnAtfWjMMMhrZVg7IXMbqeWACR'),
	'FROM_NUMBER' => env('FROM_NUMBER', 'ML-CMS'),
];
