name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: directfinding.com
        remote-user: directfinding
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: ~/public_html/client/mlcms/
